feat: useAsync swap
getnacelle/nuxt-reference-store pull request #50
Opened 2022-01-10 19:59 UTC by alexcasche

**What This PR Does**
- swaps `useAsync` for `useFetch`
- removes `onGlobalSetup` plugin, moves logic to `/layouts/default`

2022-01-10 23:24 UTC, mdarrik commented
So it looks like there's an issue fetching some of the products and not others? 

I'm seeing issues locally and in the preview with https://nuxt-reference-store-git-ls-1425-useasync-swap-nacelle.vercel.app/products/ilaria-dress 

But it shows up on the `main` branch with local dev.

2022-01-11 14:32 UTC, alexcasche commented
> So it looks like there's an issue fetching some of the products and not others?
> 
> I'm seeing issues locally and in the preview with https://nuxt-reference-store-git-ls-1425-useasync-swap-nacelle.vercel.app/products/ilaria-dress
> 
> But it shows up on the `main` branch with local dev.

@mdarrik should be all set here.

2022-01-11 14:39 UTC, NWRichmond commented
@alexcasche do you mind if we swap `feat:` to `refactor:` in the PR title? I think that's what this is, but please let me know if you think it should be a `feat:`.

2022-01-11 15:35 UTC, alexcasche commented
> @alexcasche do you mind if we swap `feat:` to `refactor:` in the PR title? I think that's what this is, but please let me know if you think it should be a `feat:`.

@NWRichmond  all set

2022-01-11 22:56 UTC, NWRichmond requested changes
Looks good! There's just one missing import in `pages/pages/_handle.vue` that's impacting pages like [`/about`](https://nuxt-reference-store-git-ls-1425-useasync-swap-nacelle.vercel.app/pages/about) and [`/contact`](https://nuxt-reference-store-git-ls-1425-useasync-swap-nacelle.vercel.app/pages/contact). Other than that, all pages worked as expected. Nicely done!

2022-01-11 22:56 UTC, NWRichmond commented on pages/pages/_handle.vue
>      const { params } = useContext();
```suggestion
    const { params, route } = useContext();
```

2022-01-11 23:14 UTC, NWRichmond commented
@alexcasche I noticed a bit of a performance regression on page-to-page transitions:

#### On `https://nuxt-reference-store.vercel.app`

https://user-images.githubusercontent.com/5732000/149035855-fdb306ec-f9b5-4e84-b3f2-7ef99348f0f7.mov

#### On `https://nuxt-reference-store-git-ls-1425-useasync-swap-nacelle.vercel.app`

https://user-images.githubusercontent.com/5732000/149036148-cc6230af-f7fd-443c-9b66-c3d74db6be09.mov

2022-01-12 01:02 UTC, NWRichmond commented
Confirmed that the deploy preview is doing client-side data fetching. Something's amiss.

#### On `https://nuxt-reference-store.vercel.app`

https://user-images.githubusercontent.com/5732000/149045389-a2517492-a638-435f-b184-43d0699ed50b.mov

#### On `https://nuxt-reference-store-git-ls-1425-useasync-swap-nacelle.vercel.app`

https://user-images.githubusercontent.com/5732000/149045354-f46cd283-7c17-4f9c-913d-15b2002a1bd4.mov

2025-09-19 13:06 UTC, closed without merging